import { ArrowUpRight, Scissors } from 'lucide-react'
import { Reviews } from './Reviews'

export function Editorial() { return <>
  <section className="arrival section"><div className="arrival-media reveal"><picture><source srcSet="/images/new-arrivals-leather.avif" type="image/avif"/><img src="/images/new-arrivals-leather.webp" alt="Крупная фактура мягкой коричневой кожи" width="1122" height="1402" loading="lazy" decoding="async"/></picture><span>Новые поступления</span></div><div className="arrival-copy reveal"><p className="kicker">02 — Новое в каталоге</p><h2>Свежие фактуры.<br/><em>Живой цвет.</em></h2><p>Ассортимент регулярно обновляется. Смотрите актуальные материалы и уточняйте наличие у менеджера.</p><a className="text-link" href="/odejnayakozha">Смотреть новинки <ArrowUpRight size={17}/></a></div></section>
  <section className="proof section" id="about"><div className="proof-intro reveal"><p className="kicker">03 — OZELIF</p><h2>Опыт в материале.<br/><em>Внимание к задаче.</em></h2></div><div className="proof-grid reveal"><div className="proof-big"><span>1000</span><p>вариантов натуральной кожи и дублёночного меха в наличии</p></div><div className="proof-list"><p><b>С 2011 года</b><span>работаем с розничными и оптовыми клиентами</span></p><p><b>Россия и ближнее зарубежье</b><span>география работы, указанная компанией</span></p><p><b>Цены производителя</b><span>официальное представительство турецкой кожевенной фабрики</span></p></div></div></section>
  <Reviews/>
  <section className="production"><picture className="production-media"><source srcSet="/images/production-workshop.avif" type="image/avif"/><img src="/images/production-workshop.webp" alt="Швейная мастерская с кожей, лекалами и инструментами" width="1672" height="941" loading="lazy" decoding="async"/></picture><div className="production-shade"/><div className="production-content reveal"><Scissors/><p className="kicker">Швейное направление</p><h2>От материала<br/>до готовой коллекции</h2><p>Собственное производство полного цикла в Москве, запущенное в 2020 году. Работа с кожей, текстилем и денимом для брендов.</p><a className="btn btn--light" href="/production">Швейное производство <ArrowUpRight size={17}/></a></div></section>
</> }
