import { BarChart3, Bot, Boxes, ChevronRight, LayoutDashboard, LogOut, Menu, PackagePlus, Search, Settings, ShoppingBag, Users, X } from 'lucide-react'
import { FormEvent, useEffect, useMemo, useState, type ReactNode } from 'react'
import { adminApi, type AdminUser, type Category, type Metrics, type Product } from './adminApi'
import './admin.css'

type Section='overview'|'catalogs'|'products'|'chats'|'analytics'|'settings'
const empty:Metrics={visitors_today:0,page_views_today:0,product_views_today:0,add_to_cart_today:0,categories_count:0,products_count:0,products_without_image:0,products_without_price:0,active_chats:0}

function Login({onLogin}:{onLogin:(u:AdminUser)=>void}){
  const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[pending,setPending]=useState(false)
  async function submit(e:FormEvent){e.preventDefault();setPending(true);setError('');try{onLogin((await adminApi.login(email,password)).user)}catch(err){setError(err instanceof Error?err.message:'Ошибка входа')}finally{setPending(false)}}
  return <main className="oa-login"><section><b>OZELIF <small>admin</small></b><div><p>Единый центр управления</p><h1>Каталоги, товары, чаты и аналитика.</h1><span>Панель для ежедневной работы с ассортиментом и будущим AI-консультантом.</span></div></section><form onSubmit={submit}><i><ShoppingBag/></i><p>Защищённый вход</p><h2>OZELIF Admin</h2><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Пароль<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<em>{error}</em>}<button disabled={pending}>{pending?'Входим…':'Войти'}<ChevronRight size={17}/></button></form></main>
}
function Metric({label,value,note,icon}:{label:string;value:number;note:string;icon:ReactNode}){return <article className="oa-metric"><i>{icon}</i><p>{label}</p><strong>{value.toLocaleString('ru-RU')}</strong><small>{note}</small></article>}

export function AdminPage(){
  const[user,setUser]=useState<AdminUser|null>(null);const[loading,setLoading]=useState(true);const[section,setSection]=useState<Section>('overview');const[mobile,setMobile]=useState(false);const[metrics,setMetrics]=useState(empty);const[catalogs,setCatalogs]=useState<Category[]>([]);const[products,setProducts]=useState<Product[]>([]);const[recent,setRecent]=useState<Array<{action:string;entity_type:string;created_at:string}>>([]);const[error,setError]=useState('')
  async function refresh(){setError('');try{const[d,c,p]=await Promise.all([adminApi.dashboard(),adminApi.catalogs(),adminApi.products()]);setMetrics(d.metrics);setRecent(d.recentActivity);setCatalogs(c.items);setProducts(p.items)}catch(err){setError(err instanceof Error?err.message:'Ошибка загрузки')}}
  useEffect(()=>{document.title='OZELIF Admin';adminApi.session().then(r=>setUser(r.user)).catch(()=>setUser(null)).finally(()=>setLoading(false))},[])
  useEffect(()=>{if(user)void refresh()},[user])
  if(loading)return <div className="oa-loading">Загружаем OZELIF Admin…</div>
  if(!user)return <Login onLogin={setUser}/>
  const nav=[['overview','Обзор',<LayoutDashboard/>],['catalogs','Каталоги',<Boxes/>],['products','Товары',<ShoppingBag/>],['chats','Чаты',<Bot/>],['analytics','Аналитика',<BarChart3/>],['settings','Настройки',<Settings/>]] as const
  return <div className="oa-app"><aside className={mobile?'is-open':''}><b className="oa-brand">OZELIF<small>admin panel</small></b><nav>{nav.map(([id,label,icon])=><button className={section===id?'is-active':''} onClick={()=>{setSection(id);setMobile(false)}} key={id}>{icon}<span>{label}</span>{id==='chats'&&metrics.active_chats>0&&<em>{metrics.active_chats}</em>}</button>)}</nav><footer><i>{user.name.slice(0,1)}</i><div><b>{user.name}</b><small>{user.email}</small></div><button onClick={()=>void adminApi.logout().finally(()=>setUser(null))}><LogOut/></button></footer></aside>{mobile&&<button className="oa-backdrop" onClick={()=>setMobile(false)}/>}<main><header><button className="oa-menu" onClick={()=>setMobile(true)}><Menu/></button><div><p>OZELIF Admin</p><h1>{nav.find(x=>x[0]===section)?.[1]}</h1></div><a href="/" target="_blank">Открыть сайт<ChevronRight/></a></header>{error&&<div className="oa-error">{error}</div>}<div className="oa-content">{section==='overview'&&<Overview metrics={metrics} recent={recent}/>} {section==='catalogs'&&<Catalogs items={catalogs} refresh={refresh}/>} {section==='products'&&<Products items={products} catalogs={catalogs} refresh={refresh}/>} {['chats','analytics','settings'].includes(section)&&<Placeholder section={section}/>}</div></main></div>
}
function Overview({metrics,recent}:{metrics:Metrics;recent:Array<{action:string;entity_type:string;created_at:string}>}){return <><section className="oa-metrics"><Metric label="Посетители сегодня" value={metrics.visitors_today} note="уникальные сессии" icon={<Users/>}/><Metric label="Просмотры страниц" value={metrics.page_views_today} note="с начала дня" icon={<BarChart3/>}/><Metric label="Просмотры товаров" value={metrics.product_views_today} note="интерес к ассортименту" icon={<ShoppingBag/>}/><Metric label="Добавления в корзину" value={metrics.add_to_cart_today} note="за текущий день" icon={<PackagePlus/>}/></section><section className="oa-grid"><article className="oa-card"><h2>Состояние каталога</h2><dl><div><dt>Каталогов</dt><dd>{metrics.categories_count}</dd></div><div><dt>Товаров</dt><dd>{metrics.products_count}</dd></div><div><dt>Без фотографии</dt><dd>{metrics.products_without_image}</dd></div><div><dt>Без цены</dt><dd>{metrics.products_without_price}</dd></div></dl></article><article className="oa-card"><h2>Последние изменения</h2>{recent.length?recent.map((x,i)=><div className="oa-log" key={i}><b>{x.action}</b><span>{x.entity_type}</span><time>{new Date(x.created_at).toLocaleString('ru-RU')}</time></div>):<p className="oa-empty">Изменений пока нет.</p>}</article></section></>}
function Catalogs({items,refresh}:{items:Category[];refresh:()=>Promise<void>}){const[open,setOpen]=useState(false);const[image,setImage]=useState('');const[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);try{await adminApi.createCatalog({name:data.get('name'),slug:data.get('slug'),description:data.get('description'),coverImage:image,isPublished:data.get('published')==='on'});e.currentTarget.reset();setImage('');setOpen(false);await refresh()}catch(err){setError(err instanceof Error?err.message:'Ошибка')}}return <section className="oa-card"><div className="oa-head"><div><p>Структура сайта</p><h2>Каталоги</h2></div><button onClick={()=>setOpen(!open)}>{open?<X/>:<Boxes/>}{open?'Закрыть':'Новый каталог'}</button></div>{open&&<form className="oa-form" onSubmit={submit}><label>Название<input name="name" required/></label><label>Адрес<input name="slug" placeholder="mebelnaya-kozha"/></label><label className="wide">Описание<textarea name="description"/></label><label>Обложка<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void adminApi.upload(f).then(r=>setImage(r.url)).catch(err=>setError(err.message))}}/></label><label className="check"><input type="checkbox" name="published"/>Опубликовать</label>{error&&<em className="wide">{error}</em>}<button type="submit">Создать каталог</button></form>}<div className="oa-table"><div><b>Каталог</b><b>Адрес</b><b>Товары</b><b>Статус</b></div>{items.map(x=><div key={x.id}><span>{x.cover_image?<img src={x.cover_image}/>:<i><Boxes/></i>}<b>{x.name}</b></span><span>/{x.slug}</span><span>{x.products_count}</span><span>{x.is_published?'Опубликован':'Черновик'}</span></div>)}</div></section>}
function Products({items,catalogs,refresh}:{items:Product[];catalogs:Category[];refresh:()=>Promise<void>}){const[open,setOpen]=useState(false);const[image,setImage]=useState('');const[q,setQ]=useState('');const[error,setError]=useState('');const visible=useMemo(()=>items.filter(x=>!q||[x.name,x.sku,x.category_name].filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase())),[items,q]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);try{await adminApi.createProduct({categoryId:d.get('categoryId'),name:d.get('name'),slug:d.get('slug'),sku:d.get('sku'),basePrice:d.get('price'),unit:d.get('unit'),primaryImage:image,isPublished:d.get('published')==='on'});e.currentTarget.reset();setImage('');setOpen(false);await refresh()}catch(err){setError(err instanceof Error?err.message:'Ошибка')}}return <section className="oa-card"><div className="oa-head"><div><p>Ассортимент</p><h2>Товары</h2></div><button onClick={()=>setOpen(!open)}>{open?<X/>:<PackagePlus/>}{open?'Закрыть':'Новый товар'}</button></div>{open&&<form className="oa-form" onSubmit={submit}><label>Каталог<select name="categoryId" required><option value="">Выберите</option>{catalogs.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Название<input name="name" required/></label><label>Адрес<input name="slug"/></label><label>Артикул<input name="sku"/></label><label>Цена<input name="price" type="number" step="0.01"/></label><label>Единица<input name="unit" placeholder="шт., фут²"/></label><label>Фото<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void adminApi.upload(f).then(r=>setImage(r.url)).catch(err=>setError(err.message))}}/></label><label className="check"><input type="checkbox" name="published"/>Опубликовать</label>{error&&<em className="wide">{error}</em>}<button type="submit">Создать товар</button></form>}<label className="oa-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Поиск по товару, артикулу или каталогу"/></label><div className="oa-table"><div><b>Товар</b><b>Каталог</b><b>Цена</b><b>Статус</b></div>{visible.map(x=><div key={x.id}><span>{x.primary_image?<img src={x.primary_image}/>:<i><ShoppingBag/></i>}<b>{x.name}</b></span><span>{x.category_name}</span><span>{x.base_price?`${Number(x.base_price).toLocaleString('ru-RU')} ₽`:'Не указана'}</span><span>{x.is_published?'Опубликован':'Черновик'}</span></div>)}</div></section>}
function Placeholder({section}:{section:Section}){const map={chats:['Чаты покупателей','Диалоги появятся после подключения AI-консультанта к серверу.'],analytics:['Расширенная аналитика','Добавим графики, популярные товары, поисковые запросы и воронку.'],settings:['Настройки','Здесь будут сотрудники, роли, уведомления и интеграции.']} as const;const item=map[section as keyof typeof map];return <section className="oa-card oa-placeholder">
<Bot/><h2>{item[0]}</h2><p>{item[1]}</p></section>}
